version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
