//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

using System.IO;
using System.Reflection;

namespace QuickFix
{
    namespace FIX42
    {
        public class MessageFactory : IMessageFactory
        {
            private static readonly DataDictionary.DataDictionary _dataDictionary;
            public DataDictionary.DataDictionary DataDictionary => _dataDictionary;

            public FIXVersion[] SupportedFIXVersions { get; } = { FIXVersion.FIX42, };

            static MessageFactory()
            {
                using (Stream stream = Assembly.GetExecutingAssembly().GetManifestResourceStream("QuickFix.FIX42.FIX42.xml"))
                {
                    _dataDictionary = new DataDictionary.DataDictionary();
                    _dataDictionary.Load(stream);
                }
            }

            public QuickFix.Message Create(string beginString, string msgType)
            {
                int mt = MsgTypes.GetMsgType(msgType);
            
                switch (mt)
                {
                    case MsgTypes.Heartbeat: return new Heartbeat();
                    case MsgTypes.Logon: return new Logon();
                    case MsgTypes.TestRequest: return new TestRequest();
                    case MsgTypes.ResendRequest: return new ResendRequest();
                    case MsgTypes.Reject: return new Reject();
                    case MsgTypes.SequenceReset: return new SequenceReset();
                    case MsgTypes.Logout: return new Logout();
                    case MsgTypes.Advertisement: return new Advertisement();
                    case MsgTypes.IndicationofInterest: return new IndicationofInterest();
                    case MsgTypes.News: return new News();
                    case MsgTypes.Email: return new Email();
                    case MsgTypes.QuoteRequest: return new QuoteRequest();
                    case MsgTypes.Quote: return new Quote();
                    case MsgTypes.MassQuote: return new MassQuote();
                    case MsgTypes.QuoteCancel: return new QuoteCancel();
                    case MsgTypes.QuoteStatusRequest: return new QuoteStatusRequest();
                    case MsgTypes.QuoteAcknowledgement: return new QuoteAcknowledgement();
                    case MsgTypes.MarketDataRequest: return new MarketDataRequest();
                    case MsgTypes.MarketDataSnapshotFullRefresh: return new MarketDataSnapshotFullRefresh();
                    case MsgTypes.MarketDataIncrementalRefresh: return new MarketDataIncrementalRefresh();
                    case MsgTypes.MarketDataRequestReject: return new MarketDataRequestReject();
                    case MsgTypes.SecurityDefinitionRequest: return new SecurityDefinitionRequest();
                    case MsgTypes.SecurityDefinition: return new SecurityDefinition();
                    case MsgTypes.SecurityStatusRequest: return new SecurityStatusRequest();
                    case MsgTypes.SecurityStatus: return new SecurityStatus();
                    case MsgTypes.TradingSessionStatusRequest: return new TradingSessionStatusRequest();
                    case MsgTypes.TradingSessionStatus: return new TradingSessionStatus();
                    case MsgTypes.NewOrderSingle: return new NewOrderSingle();
                    case MsgTypes.ExecutionReport: return new ExecutionReport();
                    case MsgTypes.DontKnowTrade: return new DontKnowTrade();
                    case MsgTypes.OrderCancelReplaceRequest: return new OrderCancelReplaceRequest();
                    case MsgTypes.OrderCancelRequest: return new OrderCancelRequest();
                    case MsgTypes.OrderCancelReject: return new OrderCancelReject();
                    case MsgTypes.OrderStatusRequest: return new OrderStatusRequest();
                    case MsgTypes.Allocation: return new Allocation();
                    case MsgTypes.AllocationACK: return new AllocationACK();
                    case MsgTypes.SettlementInstructions: return new SettlementInstructions();
                    case MsgTypes.BidRequest: return new BidRequest();
                    case MsgTypes.BidResponse: return new BidResponse();
                    case MsgTypes.NewOrderList: return new NewOrderList();
                    case MsgTypes.ListStrikePrice: return new ListStrikePrice();
                    case MsgTypes.ListStatus: return new ListStatus();
                    case MsgTypes.ListExecute: return new ListExecute();
                    case MsgTypes.ListCancelRequest: return new ListCancelRequest();
                    case MsgTypes.ListStatusRequest: return new ListStatusRequest();
                    case MsgTypes.BusinessMessageReject: return new BusinessMessageReject();
                }

                if (SupportedFIXVersions[0].IsFIXT && Message.IsAdminMsgType(msgType))
                {
                    QuickFix.Message m = new QuickFix.Message();
                    m.Header.SetField(new QuickFix.Fields.StringField(QuickFix.Fields.Tags.MsgType, msgType));
                    return m;
                }

                return new QuickFix.Message();
            }


            public Group Create(string beginString, string msgType, int correspondingFieldID)
            {
                int mt = MsgTypes.GetMsgType(msgType);
                
                switch(mt)
                {
                    case MsgTypes.Logon:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoMsgTypes: return new Logon.NoMsgTypesGroup();
                        }
                        break;
                    }

                    case MsgTypes.IndicationofInterest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoIOIQualifiers: return new IndicationofInterest.NoIOIQualifiersGroup();
                            case Tags.NoRoutingIDs: return new IndicationofInterest.NoRoutingIDsGroup();
                        }
                        break;
                    }

                    case MsgTypes.News:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoRoutingIDs: return new News.NoRoutingIDsGroup();
                            case Tags.NoRelatedSym: return new News.NoRelatedSymGroup();
                            case Tags.LinesOfText: return new News.LinesOfTextGroup();
                        }
                        break;
                    }

                    case MsgTypes.Email:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoRoutingIDs: return new Email.NoRoutingIDsGroup();
                            case Tags.NoRelatedSym: return new Email.NoRelatedSymGroup();
                            case Tags.LinesOfText: return new Email.LinesOfTextGroup();
                        }
                        break;
                    }

                    case MsgTypes.QuoteRequest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoRelatedSym: return new QuoteRequest.NoRelatedSymGroup();
                        }
                        break;
                    }

                    case MsgTypes.MassQuote:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoQuoteSets: return new MassQuote.NoQuoteSetsGroup();
                            case Tags.NoQuoteEntries: return new MassQuote.NoQuoteSetsGroup.NoQuoteEntriesGroup();
                        }
                        break;
                    }

                    case MsgTypes.QuoteCancel:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoQuoteEntries: return new QuoteCancel.NoQuoteEntriesGroup();
                        }
                        break;
                    }

                    case MsgTypes.QuoteAcknowledgement:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoQuoteSets: return new QuoteAcknowledgement.NoQuoteSetsGroup();
                            case Tags.NoQuoteEntries: return new QuoteAcknowledgement.NoQuoteSetsGroup.NoQuoteEntriesGroup();
                        }
                        break;
                    }

                    case MsgTypes.MarketDataRequest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoMDEntryTypes: return new MarketDataRequest.NoMDEntryTypesGroup();
                            case Tags.NoRelatedSym: return new MarketDataRequest.NoRelatedSymGroup();
                        }
                        break;
                    }

                    case MsgTypes.MarketDataSnapshotFullRefresh:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoMDEntries: return new MarketDataSnapshotFullRefresh.NoMDEntriesGroup();
                        }
                        break;
                    }

                    case MsgTypes.MarketDataIncrementalRefresh:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoMDEntries: return new MarketDataIncrementalRefresh.NoMDEntriesGroup();
                        }
                        break;
                    }

                    case MsgTypes.SecurityDefinitionRequest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoRelatedSym: return new SecurityDefinitionRequest.NoRelatedSymGroup();
                        }
                        break;
                    }

                    case MsgTypes.SecurityDefinition:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoRelatedSym: return new SecurityDefinition.NoRelatedSymGroup();
                        }
                        break;
                    }

                    case MsgTypes.NewOrderSingle:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoAllocs: return new NewOrderSingle.NoAllocsGroup();
                            case Tags.NoTradingSessions: return new NewOrderSingle.NoTradingSessionsGroup();
                        }
                        break;
                    }

                    case MsgTypes.ExecutionReport:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoContraBrokers: return new ExecutionReport.NoContraBrokersGroup();
                        }
                        break;
                    }

                    case MsgTypes.OrderCancelReplaceRequest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoAllocs: return new OrderCancelReplaceRequest.NoAllocsGroup();
                            case Tags.NoTradingSessions: return new OrderCancelReplaceRequest.NoTradingSessionsGroup();
                        }
                        break;
                    }

                    case MsgTypes.Allocation:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoOrders: return new Allocation.NoOrdersGroup();
                            case Tags.NoExecs: return new Allocation.NoExecsGroup();
                            case Tags.NoAllocs: return new Allocation.NoAllocsGroup();
                            case Tags.NoMiscFees: return new Allocation.NoAllocsGroup.NoMiscFeesGroup();
                        }
                        break;
                    }

                    case MsgTypes.BidRequest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoBidDescriptors: return new BidRequest.NoBidDescriptorsGroup();
                            case Tags.NoBidComponents: return new BidRequest.NoBidComponentsGroup();
                        }
                        break;
                    }

                    case MsgTypes.BidResponse:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoBidComponents: return new BidResponse.NoBidComponentsGroup();
                        }
                        break;
                    }

                    case MsgTypes.NewOrderList:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoOrders: return new NewOrderList.NoOrdersGroup();
                            case Tags.NoAllocs: return new NewOrderList.NoOrdersGroup.NoAllocsGroup();
                            case Tags.NoTradingSessions: return new NewOrderList.NoOrdersGroup.NoTradingSessionsGroup();
                        }
                        break;
                    }

                    case MsgTypes.ListStrikePrice:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoStrikes: return new ListStrikePrice.NoStrikesGroup();
                        }
                        break;
                    }

                    case MsgTypes.ListStatus:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoOrders: return new ListStatus.NoOrdersGroup();
                        }
                        break;
                    }

                }
                return null;
            }

        }
    }
}
