 
    // Generated helper templates
// QuickFIXn\Message\FIX44\FIX44.txt4
// Generated items
// QuickFIXn\Message\FIX44\CollateralInquiryAck.cs
// QuickFIXn\Message\FIX44\NetworkStatusResponse.cs
// QuickFIXn\Message\FIX44\NetworkStatusRequest.cs
// QuickFIXn\Message\FIX44\CollateralInquiry.cs
// QuickFIXn\Message\FIX44\CollateralReport.cs
// QuickFIXn\Message\FIX44\CollateralResponse.cs
// QuickFIXn\Message\FIX44\CollateralAssignment.cs
// QuickFIXn\Message\FIX44\CollateralRequest.cs
// QuickFIXn\Message\FIX44\AssignmentReport.cs
// QuickFIXn\Message\FIX44\PositionReport.cs
// QuickFIXn\Message\FIX44\RequestForPositionsAck.cs
// QuickFIXn\Message\FIX44\RequestForPositions.cs
// QuickFIXn\Message\FIX44\PositionMaintenanceReport.cs
// QuickFIXn\Message\FIX44\PositionMaintenanceRequest.cs
// QuickFIXn\Message\FIX44\RegistrationInstructionsResponse.cs
// QuickFIXn\Message\FIX44\RegistrationInstructions.cs
// QuickFIXn\Message\FIX44\TradeCaptureReportAck.cs
// QuickFIXn\Message\FIX44\TradeCaptureReport.cs
// QuickFIXn\Message\FIX44\TradeCaptureReportRequestAck.cs
// QuickFIXn\Message\FIX44\TradeCaptureReportRequest.cs
// QuickFIXn\Message\FIX44\SettlementInstructionRequest.cs
// QuickFIXn\Message\FIX44\SettlementInstructions.cs
// QuickFIXn\Message\FIX44\ConfirmationRequest.cs
// QuickFIXn\Message\FIX44\ConfirmationAck.cs
// QuickFIXn\Message\FIX44\Confirmation.cs
// QuickFIXn\Message\FIX44\AllocationReportAck.cs
// QuickFIXn\Message\FIX44\AllocationReport.cs
// QuickFIXn\Message\FIX44\AllocationInstructionAck.cs
// QuickFIXn\Message\FIX44\AllocationInstruction.cs
// QuickFIXn\Message\FIX44\ListStatusRequest.cs
// QuickFIXn\Message\FIX44\ListCancelRequest.cs
// QuickFIXn\Message\FIX44\ListExecute.cs
// QuickFIXn\Message\FIX44\ListStatus.cs
// QuickFIXn\Message\FIX44\ListStrikePrice.cs
// QuickFIXn\Message\FIX44\NewOrderList.cs
// QuickFIXn\Message\FIX44\BidResponse.cs
// QuickFIXn\Message\FIX44\BidRequest.cs
// QuickFIXn\Message\FIX44\MultilegOrderCancelReplaceRequest.cs
// QuickFIXn\Message\FIX44\NewOrderMultileg.cs
// QuickFIXn\Message\FIX44\CrossOrderCancelRequest.cs
// QuickFIXn\Message\FIX44\CrossOrderCancelReplaceRequest.cs
// QuickFIXn\Message\FIX44\NewOrderCross.cs
// QuickFIXn\Message\FIX44\OrderMassStatusRequest.cs
// QuickFIXn\Message\FIX44\OrderMassCancelReport.cs
// QuickFIXn\Message\FIX44\OrderMassCancelRequest.cs
// QuickFIXn\Message\FIX44\OrderStatusRequest.cs
// QuickFIXn\Message\FIX44\OrderCancelReject.cs
// QuickFIXn\Message\FIX44\OrderCancelRequest.cs
// QuickFIXn\Message\FIX44\OrderCancelReplaceRequest.cs
// QuickFIXn\Message\FIX44\DontKnowTrade.cs
// QuickFIXn\Message\FIX44\ExecutionReport.cs
// QuickFIXn\Message\FIX44\NewOrderSingle.cs
// QuickFIXn\Message\FIX44\TradingSessionStatus.cs
// QuickFIXn\Message\FIX44\TradingSessionStatusRequest.cs
// QuickFIXn\Message\FIX44\SecurityStatus.cs
// QuickFIXn\Message\FIX44\SecurityStatusRequest.cs
// QuickFIXn\Message\FIX44\DerivativeSecurityList.cs
// QuickFIXn\Message\FIX44\DerivativeSecurityListRequest.cs
// QuickFIXn\Message\FIX44\SecurityList.cs
// QuickFIXn\Message\FIX44\SecurityListRequest.cs
// QuickFIXn\Message\FIX44\SecurityTypes.cs
// QuickFIXn\Message\FIX44\SecurityTypeRequest.cs
// QuickFIXn\Message\FIX44\SecurityDefinition.cs
// QuickFIXn\Message\FIX44\SecurityDefinitionRequest.cs
// QuickFIXn\Message\FIX44\MarketDataRequestReject.cs
// QuickFIXn\Message\FIX44\MarketDataIncrementalRefresh.cs
// QuickFIXn\Message\FIX44\MarketDataSnapshotFullRefresh.cs
// QuickFIXn\Message\FIX44\MarketDataRequest.cs
// QuickFIXn\Message\FIX44\MassQuoteAcknowledgement.cs
// QuickFIXn\Message\FIX44\MassQuote.cs
// QuickFIXn\Message\FIX44\QuoteStatusReport.cs
// QuickFIXn\Message\FIX44\QuoteStatusRequest.cs
// QuickFIXn\Message\FIX44\QuoteCancel.cs
// QuickFIXn\Message\FIX44\Quote.cs
// QuickFIXn\Message\FIX44\RFQRequest.cs
// QuickFIXn\Message\FIX44\QuoteRequestReject.cs
// QuickFIXn\Message\FIX44\QuoteResponse.cs
// QuickFIXn\Message\FIX44\QuoteRequest.cs
// QuickFIXn\Message\FIX44\Email.cs
// QuickFIXn\Message\FIX44\News.cs
// QuickFIXn\Message\FIX44\IndicationOfInterest.cs
// QuickFIXn\Message\FIX44\Advertisement.cs
// QuickFIXn\Message\FIX44\UserResponse.cs
// QuickFIXn\Message\FIX44\UserRequest.cs
// QuickFIXn\Message\FIX44\BusinessMessageReject.cs
// QuickFIXn\Message\FIX44\Logout.cs
// QuickFIXn\Message\FIX44\SequenceReset.cs
// QuickFIXn\Message\FIX44\Reject.cs
// QuickFIXn\Message\FIX44\ResendRequest.cs
// QuickFIXn\Message\FIX44\TestRequest.cs
// QuickFIXn\Message\FIX44\Logon.cs
// QuickFIXn\Message\FIX44\Heartbeat.cs
// QuickFIXn\Message\FIX44\MessageFactory.cs
// QuickFIXn\Message\FIX44\Message.cs
 





