 
    // Generated helper templates
// QuickFIXn\Message\FIX50SP2\FIX50SP2.txt4
// Generated items
// QuickFIXn\Message\FIX50SP2\PartyDetailsListReport.cs
// QuickFIXn\Message\FIX50SP2\PartyDetailsListRequest.cs
// QuickFIXn\Message\FIX50SP2\StreamAssignmentReportACK.cs
// QuickFIXn\Message\FIX50SP2\StreamAssignmentReport.cs
// QuickFIXn\Message\FIX50SP2\StreamAssignmentRequest.cs
// QuickFIXn\Message\FIX50SP2\UserNotification.cs
// QuickFIXn\Message\FIX50SP2\OrderMassActionRequest.cs
// QuickFIXn\Message\FIX50SP2\OrderMassActionReport.cs
// QuickFIXn\Message\FIX50SP2\ApplicationMessageReport.cs
// QuickFIXn\Message\FIX50SP2\ApplicationMessageRequestAck.cs
// QuickFIXn\Message\FIX50SP2\ApplicationMessageRequest.cs
// QuickFIXn\Message\FIX50SP2\MarketDefinitionUpdateReport.cs
// QuickFIXn\Message\FIX50SP2\MarketDefinition.cs
// QuickFIXn\Message\FIX50SP2\MarketDefinitionRequest.cs
// QuickFIXn\Message\FIX50SP2\TradingSessionListUpdateReport.cs
// QuickFIXn\Message\FIX50SP2\DerivativeSecurityListUpdateReport.cs
// QuickFIXn\Message\FIX50SP2\SettlementObligationReport.cs
// QuickFIXn\Message\FIX50SP2\TradingSessionListRequest.cs
// QuickFIXn\Message\FIX50SP2\TradingSessionList.cs
// QuickFIXn\Message\FIX50SP2\ExecutionAcknowledgement.cs
// QuickFIXn\Message\FIX50SP2\AllocationInstructionAlert.cs
// QuickFIXn\Message\FIX50SP2\AdjustedPositionReport.cs
// QuickFIXn\Message\FIX50SP2\SecurityListUpdateReport.cs
// QuickFIXn\Message\FIX50SP2\SecurityDefinitionUpdateReport.cs
// QuickFIXn\Message\FIX50SP2\ContraryIntentionReport.cs
// QuickFIXn\Message\FIX50SP2\ConfirmationRequest.cs
// QuickFIXn\Message\FIX50SP2\CollateralInquiryAck.cs
// QuickFIXn\Message\FIX50SP2\UserResponse.cs
// QuickFIXn\Message\FIX50SP2\UserRequest.cs
// QuickFIXn\Message\FIX50SP2\NetworkCounterpartySystemStatusResponse.cs
// QuickFIXn\Message\FIX50SP2\NetworkCounterpartySystemStatusRequest.cs
// QuickFIXn\Message\FIX50SP2\CollateralInquiry.cs
// QuickFIXn\Message\FIX50SP2\CollateralReport.cs
// QuickFIXn\Message\FIX50SP2\CollateralResponse.cs
// QuickFIXn\Message\FIX50SP2\CollateralAssignment.cs
// QuickFIXn\Message\FIX50SP2\CollateralRequest.cs
// QuickFIXn\Message\FIX50SP2\AssignmentReport.cs
// QuickFIXn\Message\FIX50SP2\SettlementInstructionRequest.cs
// QuickFIXn\Message\FIX50SP2\ConfirmationAck.cs
// QuickFIXn\Message\FIX50SP2\AllocationReportAck.cs
// QuickFIXn\Message\FIX50SP2\AllocationReport.cs
// QuickFIXn\Message\FIX50SP2\TradeCaptureReportAck.cs
// QuickFIXn\Message\FIX50SP2\TradeCaptureReportRequestAck.cs
// QuickFIXn\Message\FIX50SP2\PositionReport.cs
// QuickFIXn\Message\FIX50SP2\RequestForPositionsAck.cs
// QuickFIXn\Message\FIX50SP2\RequestForPositions.cs
// QuickFIXn\Message\FIX50SP2\PositionMaintenanceReport.cs
// QuickFIXn\Message\FIX50SP2\PositionMaintenanceRequest.cs
// QuickFIXn\Message\FIX50SP2\Confirmation.cs
// QuickFIXn\Message\FIX50SP2\QuoteResponse.cs
// QuickFIXn\Message\FIX50SP2\QuoteStatusReport.cs
// QuickFIXn\Message\FIX50SP2\RFQRequest.cs
// QuickFIXn\Message\FIX50SP2\QuoteRequestReject.cs
// QuickFIXn\Message\FIX50SP2\OrderMassStatusRequest.cs
// QuickFIXn\Message\FIX50SP2\TradeCaptureReport.cs
// QuickFIXn\Message\FIX50SP2\TradeCaptureReportRequest.cs
// QuickFIXn\Message\FIX50SP2\MultilegOrderCancelReplace.cs
// QuickFIXn\Message\FIX50SP2\NewOrderMultileg.cs
// QuickFIXn\Message\FIX50SP2\DerivativeSecurityList.cs
// QuickFIXn\Message\FIX50SP2\DerivativeSecurityListRequest.cs
// QuickFIXn\Message\FIX50SP2\SecurityList.cs
// QuickFIXn\Message\FIX50SP2\SecurityListRequest.cs
// QuickFIXn\Message\FIX50SP2\SecurityTypes.cs
// QuickFIXn\Message\FIX50SP2\SecurityTypeRequest.cs
// QuickFIXn\Message\FIX50SP2\CrossOrderCancelRequest.cs
// QuickFIXn\Message\FIX50SP2\CrossOrderCancelReplaceRequest.cs
// QuickFIXn\Message\FIX50SP2\NewOrderCross.cs
// QuickFIXn\Message\FIX50SP2\OrderMassCancelReport.cs
// QuickFIXn\Message\FIX50SP2\OrderMassCancelRequest.cs
// QuickFIXn\Message\FIX50SP2\RegistrationInstructionsResponse.cs
// QuickFIXn\Message\FIX50SP2\RegistrationInstructions.cs
// QuickFIXn\Message\FIX50SP2\ListStrikePrice.cs
// QuickFIXn\Message\FIX50SP2\BidResponse.cs
// QuickFIXn\Message\FIX50SP2\BidRequest.cs
// QuickFIXn\Message\FIX50SP2\BusinessMessageReject.cs
// QuickFIXn\Message\FIX50SP2\MassQuote.cs
// QuickFIXn\Message\FIX50SP2\TradingSessionStatus.cs
// QuickFIXn\Message\FIX50SP2\TradingSessionStatusRequest.cs
// QuickFIXn\Message\FIX50SP2\SecurityStatus.cs
// QuickFIXn\Message\FIX50SP2\SecurityStatusRequest.cs
// QuickFIXn\Message\FIX50SP2\SecurityDefinition.cs
// QuickFIXn\Message\FIX50SP2\SecurityDefinitionRequest.cs
// QuickFIXn\Message\FIX50SP2\MassQuoteAcknowledgement.cs
// QuickFIXn\Message\FIX50SP2\QuoteStatusRequest.cs
// QuickFIXn\Message\FIX50SP2\QuoteCancel.cs
// QuickFIXn\Message\FIX50SP2\MarketDataRequestReject.cs
// QuickFIXn\Message\FIX50SP2\MarketDataIncrementalRefresh.cs
// QuickFIXn\Message\FIX50SP2\MarketDataSnapshotFullRefresh.cs
// QuickFIXn\Message\FIX50SP2\MarketDataRequest.cs
// QuickFIXn\Message\FIX50SP2\SettlementInstructions.cs
// QuickFIXn\Message\FIX50SP2\Quote.cs
// QuickFIXn\Message\FIX50SP2\QuoteRequest.cs
// QuickFIXn\Message\FIX50SP2\DontKnowTrade.cs
// QuickFIXn\Message\FIX50SP2\AllocationInstructionAck.cs
// QuickFIXn\Message\FIX50SP2\ListStatus.cs
// QuickFIXn\Message\FIX50SP2\ListStatusRequest.cs
// QuickFIXn\Message\FIX50SP2\ListExecute.cs
// QuickFIXn\Message\FIX50SP2\ListCancelRequest.cs
// QuickFIXn\Message\FIX50SP2\AllocationInstruction.cs
// QuickFIXn\Message\FIX50SP2\OrderStatusRequest.cs
// QuickFIXn\Message\FIX50SP2\OrderCancelReplaceRequest.cs
// QuickFIXn\Message\FIX50SP2\OrderCancelRequest.cs
// QuickFIXn\Message\FIX50SP2\NewOrderList.cs
// QuickFIXn\Message\FIX50SP2\NewOrderSingle.cs
// QuickFIXn\Message\FIX50SP2\Email.cs
// QuickFIXn\Message\FIX50SP2\News.cs
// QuickFIXn\Message\FIX50SP2\OrderCancelReject.cs
// QuickFIXn\Message\FIX50SP2\ExecutionReport.cs
// QuickFIXn\Message\FIX50SP2\Advertisement.cs
// QuickFIXn\Message\FIX50SP2\IOI.cs
// QuickFIXn\Message\FIX50SP2\MessageFactory.cs
// QuickFIXn\Message\FIX50SP2\Message.cs
 





