 
    // Generated helper templates
// QuickFIXn\Message\FIX50SP1\FIX50SP1.txt4
// Generated items
// QuickFIXn\Message\FIX50SP1\UserNotification.cs
// QuickFIXn\Message\FIX50SP1\OrderMassActionRequest.cs
// QuickFIXn\Message\FIX50SP1\OrderMassActionReport.cs
// QuickFIXn\Message\FIX50SP1\ApplicationMessageReport.cs
// QuickFIXn\Message\FIX50SP1\ApplicationMessageRequestAck.cs
// QuickFIXn\Message\FIX50SP1\ApplicationMessageRequest.cs
// QuickFIXn\Message\FIX50SP1\MarketDefinitionUpdateReport.cs
// QuickFIXn\Message\FIX50SP1\MarketDefinition.cs
// QuickFIXn\Message\FIX50SP1\MarketDefinitionRequest.cs
// QuickFIXn\Message\FIX50SP1\TradingSessionListUpdateReport.cs
// QuickFIXn\Message\FIX50SP1\DerivativeSecurityListUpdateReport.cs
// QuickFIXn\Message\FIX50SP1\SettlementObligationReport.cs
// QuickFIXn\Message\FIX50SP1\TradingSessionListRequest.cs
// QuickFIXn\Message\FIX50SP1\TradingSessionList.cs
// QuickFIXn\Message\FIX50SP1\ExecutionAcknowledgement.cs
// QuickFIXn\Message\FIX50SP1\AllocationInstructionAlert.cs
// QuickFIXn\Message\FIX50SP1\AdjustedPositionReport.cs
// QuickFIXn\Message\FIX50SP1\SecurityListUpdateReport.cs
// QuickFIXn\Message\FIX50SP1\SecurityDefinitionUpdateReport.cs
// QuickFIXn\Message\FIX50SP1\ContraryIntentionReport.cs
// QuickFIXn\Message\FIX50SP1\ConfirmationRequest.cs
// QuickFIXn\Message\FIX50SP1\CollateralInquiryAck.cs
// QuickFIXn\Message\FIX50SP1\UserResponse.cs
// QuickFIXn\Message\FIX50SP1\UserRequest.cs
// QuickFIXn\Message\FIX50SP1\NetworkCounterpartySystemStatusResponse.cs
// QuickFIXn\Message\FIX50SP1\NetworkCounterpartySystemStatusRequest.cs
// QuickFIXn\Message\FIX50SP1\CollateralInquiry.cs
// QuickFIXn\Message\FIX50SP1\CollateralReport.cs
// QuickFIXn\Message\FIX50SP1\CollateralResponse.cs
// QuickFIXn\Message\FIX50SP1\CollateralAssignment.cs
// QuickFIXn\Message\FIX50SP1\CollateralRequest.cs
// QuickFIXn\Message\FIX50SP1\AssignmentReport.cs
// QuickFIXn\Message\FIX50SP1\SettlementInstructionRequest.cs
// QuickFIXn\Message\FIX50SP1\ConfirmationAck.cs
// QuickFIXn\Message\FIX50SP1\AllocationReportAck.cs
// QuickFIXn\Message\FIX50SP1\AllocationReport.cs
// QuickFIXn\Message\FIX50SP1\TradeCaptureReportAck.cs
// QuickFIXn\Message\FIX50SP1\TradeCaptureReportRequestAck.cs
// QuickFIXn\Message\FIX50SP1\PositionReport.cs
// QuickFIXn\Message\FIX50SP1\RequestForPositionsAck.cs
// QuickFIXn\Message\FIX50SP1\RequestForPositions.cs
// QuickFIXn\Message\FIX50SP1\PositionMaintenanceReport.cs
// QuickFIXn\Message\FIX50SP1\PositionMaintenanceRequest.cs
// QuickFIXn\Message\FIX50SP1\Confirmation.cs
// QuickFIXn\Message\FIX50SP1\QuoteResponse.cs
// QuickFIXn\Message\FIX50SP1\QuoteStatusReport.cs
// QuickFIXn\Message\FIX50SP1\RFQRequest.cs
// QuickFIXn\Message\FIX50SP1\QuoteRequestReject.cs
// QuickFIXn\Message\FIX50SP1\OrderMassStatusRequest.cs
// QuickFIXn\Message\FIX50SP1\TradeCaptureReport.cs
// QuickFIXn\Message\FIX50SP1\TradeCaptureReportRequest.cs
// QuickFIXn\Message\FIX50SP1\MultilegOrderCancelReplace.cs
// QuickFIXn\Message\FIX50SP1\NewOrderMultileg.cs
// QuickFIXn\Message\FIX50SP1\DerivativeSecurityList.cs
// QuickFIXn\Message\FIX50SP1\DerivativeSecurityListRequest.cs
// QuickFIXn\Message\FIX50SP1\SecurityList.cs
// QuickFIXn\Message\FIX50SP1\SecurityListRequest.cs
// QuickFIXn\Message\FIX50SP1\SecurityTypes.cs
// QuickFIXn\Message\FIX50SP1\SecurityTypeRequest.cs
// QuickFIXn\Message\FIX50SP1\CrossOrderCancelRequest.cs
// QuickFIXn\Message\FIX50SP1\CrossOrderCancelReplaceRequest.cs
// QuickFIXn\Message\FIX50SP1\NewOrderCross.cs
// QuickFIXn\Message\FIX50SP1\OrderMassCancelReport.cs
// QuickFIXn\Message\FIX50SP1\OrderMassCancelRequest.cs
// QuickFIXn\Message\FIX50SP1\RegistrationInstructionsResponse.cs
// QuickFIXn\Message\FIX50SP1\RegistrationInstructions.cs
// QuickFIXn\Message\FIX50SP1\ListStrikePrice.cs
// QuickFIXn\Message\FIX50SP1\BidResponse.cs
// QuickFIXn\Message\FIX50SP1\BidRequest.cs
// QuickFIXn\Message\FIX50SP1\BusinessMessageReject.cs
// QuickFIXn\Message\FIX50SP1\MassQuote.cs
// QuickFIXn\Message\FIX50SP1\TradingSessionStatus.cs
// QuickFIXn\Message\FIX50SP1\TradingSessionStatusRequest.cs
// QuickFIXn\Message\FIX50SP1\SecurityStatus.cs
// QuickFIXn\Message\FIX50SP1\SecurityStatusRequest.cs
// QuickFIXn\Message\FIX50SP1\SecurityDefinition.cs
// QuickFIXn\Message\FIX50SP1\SecurityDefinitionRequest.cs
// QuickFIXn\Message\FIX50SP1\MassQuoteAcknowledgement.cs
// QuickFIXn\Message\FIX50SP1\QuoteStatusRequest.cs
// QuickFIXn\Message\FIX50SP1\QuoteCancel.cs
// QuickFIXn\Message\FIX50SP1\MarketDataRequestReject.cs
// QuickFIXn\Message\FIX50SP1\MarketDataIncrementalRefresh.cs
// QuickFIXn\Message\FIX50SP1\MarketDataSnapshotFullRefresh.cs
// QuickFIXn\Message\FIX50SP1\MarketDataRequest.cs
// QuickFIXn\Message\FIX50SP1\SettlementInstructions.cs
// QuickFIXn\Message\FIX50SP1\Quote.cs
// QuickFIXn\Message\FIX50SP1\QuoteRequest.cs
// QuickFIXn\Message\FIX50SP1\DontKnowTrade.cs
// QuickFIXn\Message\FIX50SP1\AllocationInstructionAck.cs
// QuickFIXn\Message\FIX50SP1\ListStatus.cs
// QuickFIXn\Message\FIX50SP1\ListStatusRequest.cs
// QuickFIXn\Message\FIX50SP1\ListExecute.cs
// QuickFIXn\Message\FIX50SP1\ListCancelRequest.cs
// QuickFIXn\Message\FIX50SP1\AllocationInstruction.cs
// QuickFIXn\Message\FIX50SP1\OrderStatusRequest.cs
// QuickFIXn\Message\FIX50SP1\OrderCancelReplaceRequest.cs
// QuickFIXn\Message\FIX50SP1\OrderCancelRequest.cs
// QuickFIXn\Message\FIX50SP1\NewOrderList.cs
// QuickFIXn\Message\FIX50SP1\NewOrderSingle.cs
// QuickFIXn\Message\FIX50SP1\Email.cs
// QuickFIXn\Message\FIX50SP1\News.cs
// QuickFIXn\Message\FIX50SP1\OrderCancelReject.cs
// QuickFIXn\Message\FIX50SP1\ExecutionReport.cs
// QuickFIXn\Message\FIX50SP1\Advertisement.cs
// QuickFIXn\Message\FIX50SP1\IOI.cs
// QuickFIXn\Message\FIX50SP1\MessageFactory.cs
// QuickFIXn\Message\FIX50SP1\Message.cs
 





