 
    // Generated helper templates
// QuickFIXn\Message\FIX50\FIX50.txt4
// Generated items
// QuickFIXn\Message\FIX50\TradingSessionListRequest.cs
// QuickFIXn\Message\FIX50\TradingSessionList.cs
// QuickFIXn\Message\FIX50\ExecutionAcknowledgement.cs
// QuickFIXn\Message\FIX50\AllocationInstructionAlert.cs
// QuickFIXn\Message\FIX50\AdjustedPositionReport.cs
// QuickFIXn\Message\FIX50\SecurityListUpdateReport.cs
// QuickFIXn\Message\FIX50\SecurityDefinitionUpdateReport.cs
// QuickFIXn\Message\FIX50\ContraryIntentionReport.cs
// QuickFIXn\Message\FIX50\ConfirmationRequest.cs
// QuickFIXn\Message\FIX50\CollateralInquiryAck.cs
// QuickFIXn\Message\FIX50\UserResponse.cs
// QuickFIXn\Message\FIX50\UserRequest.cs
// QuickFIXn\Message\FIX50\NetworkCounterpartySystemStatusResponse.cs
// QuickFIXn\Message\FIX50\NetworkCounterpartySystemStatusRequest.cs
// QuickFIXn\Message\FIX50\CollateralInquiry.cs
// QuickFIXn\Message\FIX50\CollateralReport.cs
// QuickFIXn\Message\FIX50\CollateralResponse.cs
// QuickFIXn\Message\FIX50\CollateralAssignment.cs
// QuickFIXn\Message\FIX50\CollateralRequest.cs
// QuickFIXn\Message\FIX50\AssignmentReport.cs
// QuickFIXn\Message\FIX50\SettlementInstructionRequest.cs
// QuickFIXn\Message\FIX50\ConfirmationAck.cs
// QuickFIXn\Message\FIX50\AllocationReportAck.cs
// QuickFIXn\Message\FIX50\AllocationReport.cs
// QuickFIXn\Message\FIX50\TradeCaptureReportAck.cs
// QuickFIXn\Message\FIX50\TradeCaptureReportRequestAck.cs
// QuickFIXn\Message\FIX50\PositionReport.cs
// QuickFIXn\Message\FIX50\RequestForPositionsAck.cs
// QuickFIXn\Message\FIX50\RequestForPositions.cs
// QuickFIXn\Message\FIX50\PositionMaintenanceReport.cs
// QuickFIXn\Message\FIX50\PositionMaintenanceRequest.cs
// QuickFIXn\Message\FIX50\Confirmation.cs
// QuickFIXn\Message\FIX50\QuoteResponse.cs
// QuickFIXn\Message\FIX50\QuoteStatusReport.cs
// QuickFIXn\Message\FIX50\RFQRequest.cs
// QuickFIXn\Message\FIX50\QuoteRequestReject.cs
// QuickFIXn\Message\FIX50\OrderMassStatusRequest.cs
// QuickFIXn\Message\FIX50\TradeCaptureReport.cs
// QuickFIXn\Message\FIX50\TradeCaptureReportRequest.cs
// QuickFIXn\Message\FIX50\MultilegOrderCancelReplace.cs
// QuickFIXn\Message\FIX50\NewOrderMultileg.cs
// QuickFIXn\Message\FIX50\DerivativeSecurityList.cs
// QuickFIXn\Message\FIX50\DerivativeSecurityListRequest.cs
// QuickFIXn\Message\FIX50\SecurityList.cs
// QuickFIXn\Message\FIX50\SecurityListRequest.cs
// QuickFIXn\Message\FIX50\SecurityTypes.cs
// QuickFIXn\Message\FIX50\SecurityTypeRequest.cs
// QuickFIXn\Message\FIX50\CrossOrderCancelRequest.cs
// QuickFIXn\Message\FIX50\CrossOrderCancelReplaceRequest.cs
// QuickFIXn\Message\FIX50\NewOrderCross.cs
// QuickFIXn\Message\FIX50\OrderMassCancelReport.cs
// QuickFIXn\Message\FIX50\OrderMassCancelRequest.cs
// QuickFIXn\Message\FIX50\RegistrationInstructionsResponse.cs
// QuickFIXn\Message\FIX50\RegistrationInstructions.cs
// QuickFIXn\Message\FIX50\ListStrikePrice.cs
// QuickFIXn\Message\FIX50\BidResponse.cs
// QuickFIXn\Message\FIX50\BidRequest.cs
// QuickFIXn\Message\FIX50\BusinessMessageReject.cs
// QuickFIXn\Message\FIX50\MassQuote.cs
// QuickFIXn\Message\FIX50\TradingSessionStatus.cs
// QuickFIXn\Message\FIX50\TradingSessionStatusRequest.cs
// QuickFIXn\Message\FIX50\SecurityStatus.cs
// QuickFIXn\Message\FIX50\SecurityStatusRequest.cs
// QuickFIXn\Message\FIX50\SecurityDefinition.cs
// QuickFIXn\Message\FIX50\SecurityDefinitionRequest.cs
// QuickFIXn\Message\FIX50\MassQuoteAcknowledgement.cs
// QuickFIXn\Message\FIX50\QuoteStatusRequest.cs
// QuickFIXn\Message\FIX50\QuoteCancel.cs
// QuickFIXn\Message\FIX50\MarketDataRequestReject.cs
// QuickFIXn\Message\FIX50\MarketDataIncrementalRefresh.cs
// QuickFIXn\Message\FIX50\MarketDataSnapshotFullRefresh.cs
// QuickFIXn\Message\FIX50\MarketDataRequest.cs
// QuickFIXn\Message\FIX50\SettlementInstructions.cs
// QuickFIXn\Message\FIX50\Quote.cs
// QuickFIXn\Message\FIX50\QuoteRequest.cs
// QuickFIXn\Message\FIX50\DontKnowTrade.cs
// QuickFIXn\Message\FIX50\AllocationInstructionAck.cs
// QuickFIXn\Message\FIX50\ListStatus.cs
// QuickFIXn\Message\FIX50\ListStatusRequest.cs
// QuickFIXn\Message\FIX50\ListExecute.cs
// QuickFIXn\Message\FIX50\ListCancelRequest.cs
// QuickFIXn\Message\FIX50\AllocationInstruction.cs
// QuickFIXn\Message\FIX50\OrderStatusRequest.cs
// QuickFIXn\Message\FIX50\OrderCancelReplaceRequest.cs
// QuickFIXn\Message\FIX50\OrderCancelRequest.cs
// QuickFIXn\Message\FIX50\NewOrderList.cs
// QuickFIXn\Message\FIX50\NewOrderSingle.cs
// QuickFIXn\Message\FIX50\Email.cs
// QuickFIXn\Message\FIX50\News.cs
// QuickFIXn\Message\FIX50\OrderCancelReject.cs
// QuickFIXn\Message\FIX50\ExecutionReport.cs
// QuickFIXn\Message\FIX50\Advertisement.cs
// QuickFIXn\Message\FIX50\IOI.cs
// QuickFIXn\Message\FIX50\MessageFactory.cs
// QuickFIXn\Message\FIX50\Message.cs
 





