//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------

using System.IO;
using System.Reflection;

namespace QuickFix
{
    namespace FIX43
    {
        public class MessageFactory : IMessageFactory
        {
            private static readonly DataDictionary.DataDictionary _dataDictionary;
            public DataDictionary.DataDictionary DataDictionary => _dataDictionary;

            public FIXVersion[] SupportedFIXVersions { get; } = { FIXVersion.FIX43, };

            static MessageFactory()
            {
                using (Stream stream = Assembly.GetExecutingAssembly().GetManifestResourceStream("QuickFix.FIX43.FIX43.xml"))
                {
                    _dataDictionary = new DataDictionary.DataDictionary();
                    _dataDictionary.Load(stream);
                }
            }

            public QuickFix.Message Create(string beginString, string msgType)
            {
                int mt = MsgTypes.GetMsgType(msgType);
            
                switch (mt)
                {
                    case MsgTypes.Heartbeat: return new Heartbeat();
                    case MsgTypes.Logon: return new Logon();
                    case MsgTypes.TestRequest: return new TestRequest();
                    case MsgTypes.ResendRequest: return new ResendRequest();
                    case MsgTypes.Reject: return new Reject();
                    case MsgTypes.SequenceReset: return new SequenceReset();
                    case MsgTypes.Logout: return new Logout();
                    case MsgTypes.BusinessMessageReject: return new BusinessMessageReject();
                    case MsgTypes.Advertisement: return new Advertisement();
                    case MsgTypes.IndicationOfInterest: return new IndicationOfInterest();
                    case MsgTypes.News: return new News();
                    case MsgTypes.Email: return new Email();
                    case MsgTypes.QuoteRequest: return new QuoteRequest();
                    case MsgTypes.QuoteRequestReject: return new QuoteRequestReject();
                    case MsgTypes.RFQRequest: return new RFQRequest();
                    case MsgTypes.Quote: return new Quote();
                    case MsgTypes.QuoteCancel: return new QuoteCancel();
                    case MsgTypes.QuoteStatusRequest: return new QuoteStatusRequest();
                    case MsgTypes.QuoteStatusReport: return new QuoteStatusReport();
                    case MsgTypes.MassQuote: return new MassQuote();
                    case MsgTypes.MassQuoteAcknowledgement: return new MassQuoteAcknowledgement();
                    case MsgTypes.MarketDataRequest: return new MarketDataRequest();
                    case MsgTypes.MarketDataSnapshotFullRefresh: return new MarketDataSnapshotFullRefresh();
                    case MsgTypes.MarketDataIncrementalRefresh: return new MarketDataIncrementalRefresh();
                    case MsgTypes.MarketDataRequestReject: return new MarketDataRequestReject();
                    case MsgTypes.SecurityDefinitionRequest: return new SecurityDefinitionRequest();
                    case MsgTypes.SecurityDefinition: return new SecurityDefinition();
                    case MsgTypes.SecurityTypeRequest: return new SecurityTypeRequest();
                    case MsgTypes.SecurityTypes: return new SecurityTypes();
                    case MsgTypes.SecurityListRequest: return new SecurityListRequest();
                    case MsgTypes.SecurityList: return new SecurityList();
                    case MsgTypes.DerivativeSecurityListRequest: return new DerivativeSecurityListRequest();
                    case MsgTypes.DerivativeSecurityList: return new DerivativeSecurityList();
                    case MsgTypes.SecurityStatusRequest: return new SecurityStatusRequest();
                    case MsgTypes.SecurityStatus: return new SecurityStatus();
                    case MsgTypes.TradingSessionStatusRequest: return new TradingSessionStatusRequest();
                    case MsgTypes.TradingSessionStatus: return new TradingSessionStatus();
                    case MsgTypes.NewOrderSingle: return new NewOrderSingle();
                    case MsgTypes.ExecutionReport: return new ExecutionReport();
                    case MsgTypes.DontKnowTrade: return new DontKnowTrade();
                    case MsgTypes.OrderCancelReplaceRequest: return new OrderCancelReplaceRequest();
                    case MsgTypes.OrderCancelRequest: return new OrderCancelRequest();
                    case MsgTypes.OrderCancelReject: return new OrderCancelReject();
                    case MsgTypes.OrderStatusRequest: return new OrderStatusRequest();
                    case MsgTypes.OrderMassCancelRequest: return new OrderMassCancelRequest();
                    case MsgTypes.OrderMassCancelReport: return new OrderMassCancelReport();
                    case MsgTypes.OrderMassStatusRequest: return new OrderMassStatusRequest();
                    case MsgTypes.NewOrderCross: return new NewOrderCross();
                    case MsgTypes.CrossOrderCancelReplaceRequest: return new CrossOrderCancelReplaceRequest();
                    case MsgTypes.CrossOrderCancelRequest: return new CrossOrderCancelRequest();
                    case MsgTypes.NewOrderMultileg: return new NewOrderMultileg();
                    case MsgTypes.MultilegOrderCancelReplaceRequest: return new MultilegOrderCancelReplaceRequest();
                    case MsgTypes.BidRequest: return new BidRequest();
                    case MsgTypes.BidResponse: return new BidResponse();
                    case MsgTypes.NewOrderList: return new NewOrderList();
                    case MsgTypes.ListStrikePrice: return new ListStrikePrice();
                    case MsgTypes.ListExecute: return new ListExecute();
                    case MsgTypes.ListCancelRequest: return new ListCancelRequest();
                    case MsgTypes.ListStatusRequest: return new ListStatusRequest();
                    case MsgTypes.ListStatus: return new ListStatus();
                    case MsgTypes.Allocation: return new Allocation();
                    case MsgTypes.AllocationACK: return new AllocationACK();
                    case MsgTypes.SettlementInstructions: return new SettlementInstructions();
                    case MsgTypes.TradeCaptureReportRequest: return new TradeCaptureReportRequest();
                    case MsgTypes.TradeCaptureReport: return new TradeCaptureReport();
                    case MsgTypes.RegistrationInstructions: return new RegistrationInstructions();
                    case MsgTypes.RegistrationInstructionsResponse: return new RegistrationInstructionsResponse();
                }

                if (SupportedFIXVersions[0].IsFIXT && Message.IsAdminMsgType(msgType))
                {
                    QuickFix.Message m = new QuickFix.Message();
                    m.Header.SetField(new QuickFix.Fields.StringField(QuickFix.Fields.Tags.MsgType, msgType));
                    return m;
                }

                return new QuickFix.Message();
            }


            public Group Create(string beginString, string msgType, int correspondingFieldID)
            {
                int mt = MsgTypes.GetMsgType(msgType);
                
                switch(mt)
                {
                    case MsgTypes.Logon:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoMsgTypes: return new Logon.NoMsgTypesGroup();
                        }
                        break;
                    }

                    case MsgTypes.Advertisement:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoSecurityAltID: return new Advertisement.NoSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.IndicationOfInterest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoSecurityAltID: return new IndicationOfInterest.NoSecurityAltIDGroup();
                            case Tags.NoIOIQualifiers: return new IndicationOfInterest.NoIOIQualifiersGroup();
                            case Tags.NoRoutingIDs: return new IndicationOfInterest.NoRoutingIDsGroup();
                        }
                        break;
                    }

                    case MsgTypes.News:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoRoutingIDs: return new News.NoRoutingIDsGroup();
                            case Tags.NoRelatedSym: return new News.NoRelatedSymGroup();
                            case Tags.NoSecurityAltID: return new News.NoRelatedSymGroup.NoSecurityAltIDGroup();
                            case Tags.LinesOfText: return new News.LinesOfTextGroup();
                        }
                        break;
                    }

                    case MsgTypes.Email:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoRoutingIDs: return new Email.NoRoutingIDsGroup();
                            case Tags.NoRelatedSym: return new Email.NoRelatedSymGroup();
                            case Tags.NoSecurityAltID: return new Email.NoRelatedSymGroup.NoSecurityAltIDGroup();
                            case Tags.LinesOfText: return new Email.LinesOfTextGroup();
                        }
                        break;
                    }

                    case MsgTypes.QuoteRequest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoRelatedSym: return new QuoteRequest.NoRelatedSymGroup();
                            case Tags.NoSecurityAltID: return new QuoteRequest.NoRelatedSymGroup.NoSecurityAltIDGroup();
                            case Tags.NoStipulations: return new QuoteRequest.NoRelatedSymGroup.NoStipulationsGroup();
                        }
                        break;
                    }

                    case MsgTypes.QuoteRequestReject:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoRelatedSym: return new QuoteRequestReject.NoRelatedSymGroup();
                            case Tags.NoSecurityAltID: return new QuoteRequestReject.NoRelatedSymGroup.NoSecurityAltIDGroup();
                            case Tags.NoStipulations: return new QuoteRequestReject.NoRelatedSymGroup.NoStipulationsGroup();
                        }
                        break;
                    }

                    case MsgTypes.RFQRequest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoRelatedSym: return new RFQRequest.NoRelatedSymGroup();
                            case Tags.NoSecurityAltID: return new RFQRequest.NoRelatedSymGroup.NoSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.Quote:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoPartyIDs: return new Quote.NoPartyIDsGroup();
                            case Tags.NoSecurityAltID: return new Quote.NoSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.QuoteCancel:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoPartyIDs: return new QuoteCancel.NoPartyIDsGroup();
                            case Tags.NoQuoteEntries: return new QuoteCancel.NoQuoteEntriesGroup();
                            case Tags.NoSecurityAltID: return new QuoteCancel.NoQuoteEntriesGroup.NoSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.QuoteStatusRequest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoSecurityAltID: return new QuoteStatusRequest.NoSecurityAltIDGroup();
                            case Tags.NoPartyIDs: return new QuoteStatusRequest.NoPartyIDsGroup();
                        }
                        break;
                    }

                    case MsgTypes.QuoteStatusReport:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoPartyIDs: return new QuoteStatusReport.NoPartyIDsGroup();
                            case Tags.NoSecurityAltID: return new QuoteStatusReport.NoSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.MassQuote:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoPartyIDs: return new MassQuote.NoPartyIDsGroup();
                            case Tags.NoQuoteSets: return new MassQuote.NoQuoteSetsGroup();
                            case Tags.NoUnderlyingSecurityAltID: return new MassQuote.NoQuoteSetsGroup.NoUnderlyingSecurityAltIDGroup();
                            case Tags.NoQuoteEntries: return new MassQuote.NoQuoteSetsGroup.NoQuoteEntriesGroup();
                            case Tags.NoSecurityAltID: return new MassQuote.NoQuoteSetsGroup.NoQuoteEntriesGroup.NoSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.MassQuoteAcknowledgement:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoPartyIDs: return new MassQuoteAcknowledgement.NoPartyIDsGroup();
                            case Tags.NoQuoteSets: return new MassQuoteAcknowledgement.NoQuoteSetsGroup();
                            case Tags.NoUnderlyingSecurityAltID: return new MassQuoteAcknowledgement.NoQuoteSetsGroup.NoUnderlyingSecurityAltIDGroup();
                            case Tags.NoQuoteEntries: return new MassQuoteAcknowledgement.NoQuoteSetsGroup.NoQuoteEntriesGroup();
                            case Tags.NoSecurityAltID: return new MassQuoteAcknowledgement.NoQuoteSetsGroup.NoQuoteEntriesGroup.NoSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.MarketDataRequest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoMDEntryTypes: return new MarketDataRequest.NoMDEntryTypesGroup();
                            case Tags.NoRelatedSym: return new MarketDataRequest.NoRelatedSymGroup();
                            case Tags.NoSecurityAltID: return new MarketDataRequest.NoRelatedSymGroup.NoSecurityAltIDGroup();
                            case Tags.NoTradingSessions: return new MarketDataRequest.NoTradingSessionsGroup();
                        }
                        break;
                    }

                    case MsgTypes.MarketDataSnapshotFullRefresh:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoSecurityAltID: return new MarketDataSnapshotFullRefresh.NoSecurityAltIDGroup();
                            case Tags.NoMDEntries: return new MarketDataSnapshotFullRefresh.NoMDEntriesGroup();
                        }
                        break;
                    }

                    case MsgTypes.MarketDataIncrementalRefresh:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoMDEntries: return new MarketDataIncrementalRefresh.NoMDEntriesGroup();
                            case Tags.NoSecurityAltID: return new MarketDataIncrementalRefresh.NoMDEntriesGroup.NoSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.SecurityDefinitionRequest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoSecurityAltID: return new SecurityDefinitionRequest.NoSecurityAltIDGroup();
                            case Tags.NoLegs: return new SecurityDefinitionRequest.NoLegsGroup();
                            case Tags.NoLegSecurityAltID: return new SecurityDefinitionRequest.NoLegsGroup.NoLegSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.SecurityDefinition:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoSecurityAltID: return new SecurityDefinition.NoSecurityAltIDGroup();
                            case Tags.NoLegs: return new SecurityDefinition.NoLegsGroup();
                            case Tags.NoLegSecurityAltID: return new SecurityDefinition.NoLegsGroup.NoLegSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.SecurityTypes:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoSecurityTypes: return new SecurityTypes.NoSecurityTypesGroup();
                        }
                        break;
                    }

                    case MsgTypes.SecurityListRequest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoSecurityAltID: return new SecurityListRequest.NoSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.SecurityList:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoRelatedSym: return new SecurityList.NoRelatedSymGroup();
                            case Tags.NoSecurityAltID: return new SecurityList.NoRelatedSymGroup.NoSecurityAltIDGroup();
                            case Tags.NoLegs: return new SecurityList.NoRelatedSymGroup.NoLegsGroup();
                            case Tags.NoLegSecurityAltID: return new SecurityList.NoRelatedSymGroup.NoLegsGroup.NoLegSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.DerivativeSecurityListRequest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoUnderlyingSecurityAltID: return new DerivativeSecurityListRequest.NoUnderlyingSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.DerivativeSecurityList:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoUnderlyingSecurityAltID: return new DerivativeSecurityList.NoUnderlyingSecurityAltIDGroup();
                            case Tags.NoRelatedSym: return new DerivativeSecurityList.NoRelatedSymGroup();
                            case Tags.NoSecurityAltID: return new DerivativeSecurityList.NoRelatedSymGroup.NoSecurityAltIDGroup();
                            case Tags.NoLegs: return new DerivativeSecurityList.NoRelatedSymGroup.NoLegsGroup();
                            case Tags.NoLegSecurityAltID: return new DerivativeSecurityList.NoRelatedSymGroup.NoLegsGroup.NoLegSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.SecurityStatusRequest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoSecurityAltID: return new SecurityStatusRequest.NoSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.SecurityStatus:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoSecurityAltID: return new SecurityStatus.NoSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.NewOrderSingle:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoPartyIDs: return new NewOrderSingle.NoPartyIDsGroup();
                            case Tags.NoAllocs: return new NewOrderSingle.NoAllocsGroup();
                            case Tags.NoNestedPartyIDs: return new NewOrderSingle.NoAllocsGroup.NoNestedPartyIDsGroup();
                            case Tags.NoTradingSessions: return new NewOrderSingle.NoTradingSessionsGroup();
                            case Tags.NoSecurityAltID: return new NewOrderSingle.NoSecurityAltIDGroup();
                            case Tags.NoStipulations: return new NewOrderSingle.NoStipulationsGroup();
                        }
                        break;
                    }

                    case MsgTypes.ExecutionReport:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoPartyIDs: return new ExecutionReport.NoPartyIDsGroup();
                            case Tags.NoContraBrokers: return new ExecutionReport.NoContraBrokersGroup();
                            case Tags.NoSecurityAltID: return new ExecutionReport.NoSecurityAltIDGroup();
                            case Tags.NoStipulations: return new ExecutionReport.NoStipulationsGroup();
                            case Tags.NoContAmts: return new ExecutionReport.NoContAmtsGroup();
                            case Tags.NoLegs: return new ExecutionReport.NoLegsGroup();
                            case Tags.NoLegSecurityAltID: return new ExecutionReport.NoLegsGroup.NoLegSecurityAltIDGroup();
                            case Tags.NoNestedPartyIDs: return new ExecutionReport.NoLegsGroup.NoNestedPartyIDsGroup();
                        }
                        break;
                    }

                    case MsgTypes.DontKnowTrade:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoSecurityAltID: return new DontKnowTrade.NoSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.OrderCancelReplaceRequest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoPartyIDs: return new OrderCancelReplaceRequest.NoPartyIDsGroup();
                            case Tags.NoAllocs: return new OrderCancelReplaceRequest.NoAllocsGroup();
                            case Tags.NoNestedPartyIDs: return new OrderCancelReplaceRequest.NoAllocsGroup.NoNestedPartyIDsGroup();
                            case Tags.NoTradingSessions: return new OrderCancelReplaceRequest.NoTradingSessionsGroup();
                            case Tags.NoSecurityAltID: return new OrderCancelReplaceRequest.NoSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.OrderCancelRequest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoPartyIDs: return new OrderCancelRequest.NoPartyIDsGroup();
                            case Tags.NoSecurityAltID: return new OrderCancelRequest.NoSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.OrderStatusRequest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoPartyIDs: return new OrderStatusRequest.NoPartyIDsGroup();
                            case Tags.NoSecurityAltID: return new OrderStatusRequest.NoSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.OrderMassCancelRequest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoSecurityAltID: return new OrderMassCancelRequest.NoSecurityAltIDGroup();
                            case Tags.NoUnderlyingSecurityAltID: return new OrderMassCancelRequest.NoUnderlyingSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.OrderMassCancelReport:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoAffectedOrders: return new OrderMassCancelReport.NoAffectedOrdersGroup();
                            case Tags.NoSecurityAltID: return new OrderMassCancelReport.NoSecurityAltIDGroup();
                            case Tags.NoUnderlyingSecurityAltID: return new OrderMassCancelReport.NoUnderlyingSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.OrderMassStatusRequest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoPartyIDs: return new OrderMassStatusRequest.NoPartyIDsGroup();
                            case Tags.NoSecurityAltID: return new OrderMassStatusRequest.NoSecurityAltIDGroup();
                            case Tags.NoUnderlyingSecurityAltID: return new OrderMassStatusRequest.NoUnderlyingSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.NewOrderCross:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoSides: return new NewOrderCross.NoSidesGroup();
                            case Tags.NoPartyIDs: return new NewOrderCross.NoSidesGroup.NoPartyIDsGroup();
                            case Tags.NoAllocs: return new NewOrderCross.NoSidesGroup.NoAllocsGroup();
                            case Tags.NoNestedPartyIDs: return new NewOrderCross.NoSidesGroup.NoAllocsGroup.NoNestedPartyIDsGroup();
                            case Tags.NoSecurityAltID: return new NewOrderCross.NoSecurityAltIDGroup();
                            case Tags.NoTradingSessions: return new NewOrderCross.NoTradingSessionsGroup();
                            case Tags.NoStipulations: return new NewOrderCross.NoStipulationsGroup();
                        }
                        break;
                    }

                    case MsgTypes.CrossOrderCancelReplaceRequest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoSides: return new CrossOrderCancelReplaceRequest.NoSidesGroup();
                            case Tags.NoPartyIDs: return new CrossOrderCancelReplaceRequest.NoSidesGroup.NoPartyIDsGroup();
                            case Tags.NoAllocs: return new CrossOrderCancelReplaceRequest.NoSidesGroup.NoAllocsGroup();
                            case Tags.NoNestedPartyIDs: return new CrossOrderCancelReplaceRequest.NoSidesGroup.NoAllocsGroup.NoNestedPartyIDsGroup();
                            case Tags.NoSecurityAltID: return new CrossOrderCancelReplaceRequest.NoSecurityAltIDGroup();
                            case Tags.NoTradingSessions: return new CrossOrderCancelReplaceRequest.NoTradingSessionsGroup();
                            case Tags.NoStipulations: return new CrossOrderCancelReplaceRequest.NoStipulationsGroup();
                        }
                        break;
                    }

                    case MsgTypes.CrossOrderCancelRequest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoSides: return new CrossOrderCancelRequest.NoSidesGroup();
                            case Tags.NoPartyIDs: return new CrossOrderCancelRequest.NoSidesGroup.NoPartyIDsGroup();
                            case Tags.NoSecurityAltID: return new CrossOrderCancelRequest.NoSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.NewOrderMultileg:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoPartyIDs: return new NewOrderMultileg.NoPartyIDsGroup();
                            case Tags.NoAllocs: return new NewOrderMultileg.NoAllocsGroup();
                            case Tags.NoTradingSessions: return new NewOrderMultileg.NoTradingSessionsGroup();
                            case Tags.NoSecurityAltID: return new NewOrderMultileg.NoSecurityAltIDGroup();
                            case Tags.NoLegs: return new NewOrderMultileg.NoLegsGroup();
                            case Tags.NoLegSecurityAltID: return new NewOrderMultileg.NoLegsGroup.NoLegSecurityAltIDGroup();
                            case Tags.NoNestedPartyIDs: return new NewOrderMultileg.NoLegsGroup.NoNestedPartyIDsGroup();
                        }
                        break;
                    }

                    case MsgTypes.MultilegOrderCancelReplaceRequest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoPartyIDs: return new MultilegOrderCancelReplaceRequest.NoPartyIDsGroup();
                            case Tags.NoAllocs: return new MultilegOrderCancelReplaceRequest.NoAllocsGroup();
                            case Tags.NoTradingSessions: return new MultilegOrderCancelReplaceRequest.NoTradingSessionsGroup();
                            case Tags.NoSecurityAltID: return new MultilegOrderCancelReplaceRequest.NoSecurityAltIDGroup();
                            case Tags.NoLegs: return new MultilegOrderCancelReplaceRequest.NoLegsGroup();
                            case Tags.NoLegSecurityAltID: return new MultilegOrderCancelReplaceRequest.NoLegsGroup.NoLegSecurityAltIDGroup();
                            case Tags.NoNestedPartyIDs: return new MultilegOrderCancelReplaceRequest.NoLegsGroup.NoNestedPartyIDsGroup();
                        }
                        break;
                    }

                    case MsgTypes.BidRequest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoBidDescriptors: return new BidRequest.NoBidDescriptorsGroup();
                            case Tags.NoBidComponents: return new BidRequest.NoBidComponentsGroup();
                        }
                        break;
                    }

                    case MsgTypes.BidResponse:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoBidComponents: return new BidResponse.NoBidComponentsGroup();
                        }
                        break;
                    }

                    case MsgTypes.NewOrderList:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoOrders: return new NewOrderList.NoOrdersGroup();
                            case Tags.NoPartyIDs: return new NewOrderList.NoOrdersGroup.NoPartyIDsGroup();
                            case Tags.NoAllocs: return new NewOrderList.NoOrdersGroup.NoAllocsGroup();
                            case Tags.NoNestedPartyIDs: return new NewOrderList.NoOrdersGroup.NoAllocsGroup.NoNestedPartyIDsGroup();
                            case Tags.NoTradingSessions: return new NewOrderList.NoOrdersGroup.NoTradingSessionsGroup();
                            case Tags.NoSecurityAltID: return new NewOrderList.NoOrdersGroup.NoSecurityAltIDGroup();
                            case Tags.NoStipulations: return new NewOrderList.NoOrdersGroup.NoStipulationsGroup();
                        }
                        break;
                    }

                    case MsgTypes.ListStrikePrice:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoStrikes: return new ListStrikePrice.NoStrikesGroup();
                            case Tags.NoSecurityAltID: return new ListStrikePrice.NoStrikesGroup.NoSecurityAltIDGroup();
                        }
                        break;
                    }

                    case MsgTypes.ListStatus:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoOrders: return new ListStatus.NoOrdersGroup();
                        }
                        break;
                    }

                    case MsgTypes.Allocation:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoOrders: return new Allocation.NoOrdersGroup();
                            case Tags.NoExecs: return new Allocation.NoExecsGroup();
                            case Tags.NoSecurityAltID: return new Allocation.NoSecurityAltIDGroup();
                            case Tags.NoPartyIDs: return new Allocation.NoPartyIDsGroup();
                            case Tags.NoAllocs: return new Allocation.NoAllocsGroup();
                            case Tags.NoNestedPartyIDs: return new Allocation.NoAllocsGroup.NoNestedPartyIDsGroup();
                            case Tags.NoMiscFees: return new Allocation.NoAllocsGroup.NoMiscFeesGroup();
                        }
                        break;
                    }

                    case MsgTypes.AllocationACK:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoPartyIDs: return new AllocationACK.NoPartyIDsGroup();
                        }
                        break;
                    }

                    case MsgTypes.SettlementInstructions:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoPartyIDs: return new SettlementInstructions.NoPartyIDsGroup();
                        }
                        break;
                    }

                    case MsgTypes.TradeCaptureReportRequest:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoPartyIDs: return new TradeCaptureReportRequest.NoPartyIDsGroup();
                            case Tags.NoSecurityAltID: return new TradeCaptureReportRequest.NoSecurityAltIDGroup();
                            case Tags.NoDates: return new TradeCaptureReportRequest.NoDatesGroup();
                        }
                        break;
                    }

                    case MsgTypes.TradeCaptureReport:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoSecurityAltID: return new TradeCaptureReport.NoSecurityAltIDGroup();
                            case Tags.NoSides: return new TradeCaptureReport.NoSidesGroup();
                            case Tags.NoPartyIDs: return new TradeCaptureReport.NoSidesGroup.NoPartyIDsGroup();
                            case Tags.NoClearingInstructions: return new TradeCaptureReport.NoSidesGroup.NoClearingInstructionsGroup();
                            case Tags.NoContAmts: return new TradeCaptureReport.NoSidesGroup.NoContAmtsGroup();
                            case Tags.NoMiscFees: return new TradeCaptureReport.NoSidesGroup.NoMiscFeesGroup();
                        }
                        break;
                    }

                    case MsgTypes.RegistrationInstructions:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoPartyIDs: return new RegistrationInstructions.NoPartyIDsGroup();
                            case Tags.NoRegistDtls: return new RegistrationInstructions.NoRegistDtlsGroup();
                            case Tags.NoNestedPartyIDs: return new RegistrationInstructions.NoRegistDtlsGroup.NoNestedPartyIDsGroup();
                            case Tags.NoDistribInsts: return new RegistrationInstructions.NoDistribInstsGroup();
                        }
                        break;
                    }

                    case MsgTypes.RegistrationInstructionsResponse:
                    {
                        switch (correspondingFieldID)
                        {
                            case Tags.NoPartyIDs: return new RegistrationInstructionsResponse.NoPartyIDsGroup();
                        }
                        break;
                    }

                }
                return null;
            }

        }
    }
}
